name: CPSApp
options:
  bundleIdPrefix: com.heiloprojects
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
packages:
  RadioCore:
    path: ../Packages/RadioCore
  RadioModels:
    path: ../Packages/RadioModels
  RadioHardware:
    path: ../Packages/RadioHardware
  AudioEngine:
    path: ../Packages/AudioEngine
targets:
  CPSApp:
    type: application
    platform: macOS
    sources:
      - Sources
    resources:
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.heiloprojects.MotorolaCPS
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: false
        SWIFT_VERSION: "5.9"
    dependencies:
      - package: RadioCore
      - package: RadioModels
        product: RadioModels
      - package: RadioHardware
        product: RadioHardware
      - package: AudioEngine
