#!/bin/bash
# MotorolaCPS Task Assignment Script
# Generated by Vulcan - 2026-02-06
#
# This script spawns Claude agent sessions for all pending tasks.
# Run this script to start parallel work on all domains.

PROJECT_PATH="/Users/home/Documents/Development/MotorolaCPS"

spawn_agent() {
    local agent="$1"
    local tasks="$2"
    local prompt="$3"
    
    osascript <<EOF
tell application "Terminal"
    activate
    do script "cd '$PROJECT_PATH' && claude --dangerously-skip-permissions -p \"You are $agent, part of the Pantheon agent team.

The following tasks require your attention:
$tasks

$prompt

Begin working on these tasks. Update task status to 'in_progress' when starting and 'done' when complete.\""
end tell
EOF
    sleep 2  # Brief pause between spawns
}

echo "Spawning Pantheon agents for MotorolaCPS tasks..."

# Themis - Legal/Compliance (8 tasks)
spawn_agent "Themis" \
"TASK-080: [CRITICAL] Create LEGAL.md disclaimer
TASK-081: [CRITICAL] GPL-2.0 license compliance
TASK-082: [HIGH] Create project LICENSE file  
TASK-083: [HIGH] Create Terms of Service
TASK-084: [HIGH] Audit encryption keys
TASK-085: [HIGH] Add third-party license notices
TASK-086: [MEDIUM] Update Privacy Policy
TASK-109: [LOW] Add FCC regulatory compliance warning (blocked)" \
"Focus on the CRITICAL tasks first (TASK-080, TASK-081). These establish the legal foundation for the reverse engineering project."

# Talos - Security/Performance (2 tasks)
spawn_agent "Talos" \
"TASK-087: Strengthen password derivation with PBKDF2
TASK-079: Optimize UTF-16LE string scanning" \
"TASK-087 is security-critical - the current SHA-256 single hash is vulnerable. Implement PBKDF2 with proper salt and iterations."

# Aegis - Testing (2 tasks)
spawn_agent "Aegis" \
"TASK-088: Add UI test suite for CPSApp
TASK-091: Add integration tests for read/write workflows" \
"Create comprehensive test coverage for critical radio programming workflows. Use mock connections for hardware-independent testing."

# Vulcan - Code Quality (4 tasks)
spawn_agent "Vulcan" \
"TASK-089: Replace print() with os.Logger
TASK-090: Add SwiftLint configuration
TASK-092: Document test strategy and coverage goals
TASK-110: Remove extracted CPS binaries from repository" \
"Focus on code quality infrastructure. The 594 print() statements need structured logging."

# Lumen - UX/Accessibility (7 tasks)
spawn_agent "Lumen" \
"TASK-093: Add VoiceOver rotor support
TASK-094: Improve error messages with actionable guidance
TASK-095: Add progress feedback for long-running operations
TASK-096: Complete keyboard navigation support
TASK-097: Add contextual help tooltips for technical terms
TASK-098: Improve CSV import/export documentation
TASK-099: Standardize loading states across views" \
"Focus on accessibility first (TASK-093, TASK-096). VoiceOver users and keyboard-only users need proper support."

# Clio - Documentation (3 tasks)
spawn_agent "Clio" \
"TASK-107: Update Security Model documentation
TASK-108: Create CONTRIBUTING.md with clean-room guidelines
TASK-111: Documentation Review - comprehensive assessment" \
"Start with TASK-111 to assess the full documentation landscape, then prioritize TASK-108 for contributor guidelines."

# Echo - Copy (1 task)
spawn_agent "Echo" \
"TASK-112: Copy & Messaging Review" \
"Audit all user-facing strings, error messages, and UI labels. Focus on clarity, actionability, and consistent tone."

# Athena - Knowledge (1 task)
spawn_agent "Athena" \
"TASK-113: Patterns & Knowledge Review" \
"Identify reusable patterns (binary parsing, protocol implementation) and capture lessons learned from this reverse engineering project."

# Iris - Market Research (1 task)
spawn_agent "Iris" \
"TASK-114: Market Positioning Review" \
"Assess competitive landscape (official Motorola CPS, CHIRP, etc.) and identify RadioWriter's unique value proposition."

echo ""
echo "All agents spawned. Monitor Terminal windows for progress."
echo "Tasks will update their status in .claude/epic/tasks/"
